service: timeclock-app-report

provider:
  name: aws
  runtime: nodejs4.3

functions:
  sendreport:
    handler: handler.sendreport
    events:
      - http:
          path: sendreport
          method: post
          cros: true
          integration: lambda
      - schedule: cron(0 6 ? * MON *)

plugins:
  - serverless-run-function-plugin