service: timeclock-app-report

provider:
  name: aws
  runtime: nodejs4.3

functions:
  sendreport:
    handler: handler.sendreport

  events:
     - http:
         path: sendreport
         method: get
     - schedule: cron(0 6 ? * MON *)

plugins:
  - serverless-run-function-plugin